version: 2.1
orbs:
  android: circleci/android@2.1.2

commands:
  detox_build_ios:
    steps:
      - restore_cache:
          keys:
            - ios-build-cache-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/package.json" }}
      - run:
          name: Build iOS app
          command: detox build -c ios
      - save_cache:
          key: ios-build-cache-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/package.json" }}
          paths:
            - ios/build/Build

  detox_build_android:
    steps:
      - android/restore-gradle-cache
      - run:
          name: Build Android app
          command: detox build -c android
      - android/save-gradle-cache

jobs:
  test_ios:
    macos:
      xcode: 13.2.1

    steps:
      - checkout
      - run:
          name: Install JS dependencies
          command: yarn install
      - run:
          name: Install CLI
          command: npm install -g detox-cli
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Install tools for Detox work
          command: brew tap wix/brew && brew install applesimutils
      - run:
          name: Install iOS dependencies
          command: cd ios && pod install
      - detox_build_ios
      - run:
          name: Run Detox tests
          command: detox test -c ios --cleanup
      - store_artifacts:
          path: ./e2e/test-artifacts
      - store_artifacts:
          path: ./e2e/allure-results

  test_android:
    executor:
      name: android/android-machine
      tag: 2022.08.1
      resource-class: large
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: npm install yarn -g
      - run:
          name: Install JS dependencies
          command: yarn install
      - run:
          name: Install CLI
          command: npm install -g detox-cli react-native-cli
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - android/create-avd:
          avd-name: Pixel_2_API_29
          system-image: system-images;android-29;default;x86
          install: true
      - run:
          name: Launch Emulator
          command: |
            cd ${ANDROID_HOME}/emulator;ls
            export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
            emulator -avd Pixel_2_API_29 -no-window -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Wait for emulator to start
          command: circle-android wait-for-boot
      - detox_build_android
      - run:
          name: Run Detox tests
          command: detox test -c android --headless
      - store_artifacts:
          path: ./e2e/test-artifacts
      - store_artifacts:
          path: ./e2e/allure-results

workflows:
  build_and_test:
    jobs:
      - test_ios
      - test_android

