version: 2.1

orbs:
  node: circleci/node@4.7.0
  android: circleci/android@1.0.3
  rn: react-native-community/react-native@7.1.1

jobs:
  build_ios:
    executor:
      name: rn/macos
      xcode_version: 13.2.1

    steps:
      - checkout
      - run:
          name: Install JS dependencies
          command: yarn install
      - run:
          name: Install CLI
          command: npm install -g detox-cli
      - run:
          name: Install tools for Detox work
          command: brew tap wix/brew && brew install applesimutils
      - run:
          name: Install iOS dependencies
          command: cd ios && pod install
      - run:
          name: Build app
          command: detox build -c ios
      - run:
          name: Run Detox tests
          command: detox test -c ios --cleanup
      - store_artifacts:
          path: ./e2e/test-artifacts
      - store_artifacts:
          path: ./e2e/allure-results

  build:
    executor:
      name: android/android-machine
      resource-class: large
    steps:
      - checkout
      - node/install-yarn
      - run:
          name: Install JS dependencies
          command: rn/yarn_install
      - run:
          name: Install CLI
          command: npm install -g detox-cli react-native-cli

     # - run:
     #     name: Setup emulator
     #     command: sdkmanager "system-images;android-29;default;x86" && echo "no" | avdmanager create avd -n Pixel_2_API_29 -k "system-images;android-29;default;x86"
     # - run:
      #    name: Launch emulator
     #     command: |
     #       cd ${ANDROID_HOME}/emulator;ls
     #       export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
     #       emulator -avd Pixel_2_API_29 -no-window -noaudio -no-boot-anim -no-window -accel on
     #     background: true
      - rn/android_emulator_start:
          device_name: Pixel_2_API_29_x86
      - run:
          name: Wait for emulator to start
          command: circle-android wait-for-boot
      - run:
          name: Build app
          command: detox build -c android
      - run:
          name: Run Detox tests
          command: detox test -c android --headless
      - store_artifacts:
          path: ./e2e/test-artifacts
      - store_artifacts:
          path: ./e2e/allure-results



