version: 2.1
orbs:
  android: circleci/android@2.1.2

jobs:
  build_ios:
    macos:
      xcode: 13.2.1

    steps:
      - checkout
      - run:
          name: Install JS dependencies
          command: yarn install
      - run:
          name: Install CLI
          command: npm install -g detox-cli
      - run:
          name: Install tools for Detox work
          command: brew tap wix/brew && brew install applesimutils
      - run:
          name: Install iOS dependencies
          command: cd ios && pod install
      - run:
          name: Build app
          command: detox build -c ios
      - run:
          name: Run Detox tests
          command: detox test -c ios --cleanup
      - store_artifacts:
          path: ./e2e/test-artifacts
      - store_artifacts:
          path: ./e2e/allure-results

  build:
    executor:
      name: android/android-machine
      tag: 2022.08.1-node
      resource-class: large
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: npm install yarn -g
      - run:
          name: Install JS dependencies
          command: yarn install
      - run:
          name: Install CLI
          command: npm install -g detox-cli react-native-cli
      - android/create-avd:
          avd-name: Pixel_2_API_29
          system-image: system-images;android-29;default;x86
          install: true
      - android/start-emulator:
          avd-name: Pixel_2_API_29
          no-window: true
          restore-gradle-cache-prefix: v1a
      - run:
          name: Wait for emulator to start
          command: circle-android wait-for-boot
      - run:
          name: Build app
          command: detox build -c android
      - android/save-gradle-cache:
          cache-prefix: v1a
      - run:
          name: Run Detox tests
          command: detox test -c android --headless
      - store_artifacts:
          path: ./e2e/test-artifacts
      - store_artifacts:
          path: ./e2e/allure-results



